apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdaas-sample-app
  annotations:
    "app": "cdaas-sample-app"
spec:
  revisionHistoryLimit: 1
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: cdaas-sample-app
  template:
    metadata:
      labels:
        app: cdaas-sample-app
      annotations:
        "app": "cdaas-sample-app"
    spec:
      containers:
        #- image:  demoimages/bluegreen:v4 #v5, v4, v3
        - image: asherlab/cicd-armory:blue
          imagePullPolicy: Always
          name: cdaas-sample-app
          resources:
            limits:
              cpu: "100m" # this is to ensure the above busy wait cannot DOS a low CPU cluster.
              memory: "240Mi"
            requests:
              cpu: "50m" # this is to ensure the above busy wait cannot DOS a low CPU cluster.
              memory: "140Mi"
          #ports:
          #  - containerPort: 8086
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cdaas-sample-app-svc
  labels:
    app: cdaas-sample-app
  annotations:
    linkerd.io/inject: enabled
spec:
  selector:
    app: cdaas-sample-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      #targetPort: 8000
      targetPort: 80
      protocol: TCP
