name: CI for Spring Boot

on:
  push:
    branches:
      - main

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project with Maven
        uses: docker://maven:3.8.7-eclipse-temurin-17-alpine
        with:
          args: mvn clean verify

      - name: Build project with Maven 2
        uses: docker://maven:3.8.7-eclipse-temurin-17-alpine
        with:
          args: mvn clean verify

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: asherlab/cicd-armory:latest
