name: CI/CD for Spring Boot application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build and test
      run: mvn clean install

    - name: Deploy to test environment
      uses: actions/upload-artifact@v1
      with:
        name: application-${{ env.BUILD_NUMBER }}.jar
        path: target/application.jar
