name: CI/CD for Spring Boot application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build application
        run: mvn clean package

      - name: Deploy to test environment
        uses: actions/upload-artifact@v1
        with:
          name: application-${{ env.BUILD_NUMBER }}.jar
          path: target/application.jar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v1
        with:
          name: application-${{ env.BUILD_NUMBER }}.jar

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Test application
        run: mvn test
